### ISSUE TITLE
Segfault on non-state ^operator attribute from negated conditions

### ISSUE THREAD

**Issue by justinnhli** [SoarGroup/Soar#196]
The following agent causes Soar to hard crash on both 9.4.0 release (equivalently, master on github) and on the development branch:

```
sp {rule-1
   (state <s> ^superstate nil)
-->
   (<s> ^foo <foo>)
}

sp {rule-2
   (state <s> ^foo <foo>)
   (<foo> -^bar)
-->
   (<s> ^baz.operator <o>)
   #(<s> ^baz.whatever <o>)
}
```

Note that Soar does not crash if the `whatever` action is used instead of the `operator` condition. The backtrace from gdb suggests it's a rete issue:

```
Segmentation fault: 11
0xb7b5c0b1 in get_symbol_from_rete_loc (levels_up=0, field_num=0 '\000', tok=0x80ab5b0, w=0x0) at Core/SoarKernel/src/rete.cpp:5265
#0  0xb7b5c0b1 in get_symbol_from_rete_loc (levels_up=0, field_num=0 '\000', tok=0x80ab5b0, w=0x0) at Core/SoarKernel/src/rete.cpp:5265
#1  0xb7b5e713 in p_node_left_addition (thisAgent=0x805bea8, node=0x80a3638, tok=0x80ab5b0, w=0x0) at Core/SoarKernel/src/rete.cpp:6862
#2  0xb7b5daaa in negative_node_left_addition (thisAgent=0x805bea8, node=0x80a3608, tok=0x80ab540, w=0x80bce1c) at Core/SoarKernel/src/rete.cpp:6349
#3  0xb7b5d474 in unhashed_positive_node_right_addition (thisAgent=0x805bea8, node=0x80a35d8, w=0x80bce1c) at Core/SoarKernel/src/rete.cpp:6136
#4  0xb7b56db8 in add_wme_to_aht (thisAgent=0x805bea8, ht=0x8083264, hash_value=0, w=0x80bce1c) at Core/SoarKernel/src/rete.cpp:1690
#5  0xb7b5708e in add_wme_to_rete (thisAgent=0x805bea8, w=0x80bce1c) at Core/SoarKernel/src/rete.cpp:1738
#6  0xb7b8590c in do_buffered_wm_changes (thisAgent=0x805bea8) at Core/SoarKernel/src/wmem.cpp:234
#7  0xb7b2245c in do_buffered_wm_and_ownership_changes (thisAgent=0x805bea8) at Core/SoarKernel/src/decide.cpp:3369
#8  0xb7b22588 in do_working_memory_phase (thisAgent=0x805bea8) at Core/SoarKernel/src/decide.cpp:3398
#9  0xb7b3942d in do_one_top_level_phase (thisAgent=0x805bea8) at Core/SoarKernel/src/init_soar.cpp:752
#10 0xb7b3af18 in run_for_n_decision_cycles (thisAgent=0x805bea8, n=1) at Core/SoarKernel/src/init_soar.cpp:1546
#11 0xb7cb5b35 in sml::AgentSML::Step (this=0x8069bb0, stepSize=sml::sml_DECISION) at Core/KernelSML/src/sml_AgentSML.cpp:507
#12 0xb7cb5923 in sml::AgentSML::StepInClientThread (this=0x8069bb0, stepSize=sml::sml_DECISION) at Core/KernelSML/src/sml_AgentSML.cpp:453
#13 0xb7cc56a6 in sml::RunScheduler::RunScheduledAgents (this=0x8059698, forever=false, runStepSize=sml::sml_DECISION, count=9, runFlags=sml::sml_RUN_ALL, interleaveStepSize=sml::sml_DECISION, synchronize=true) at Core/KernelSML/src/sml_RunScheduler.cpp:843
#14 0xb7d48a98 in cli::CommandLineInterface::DoRun (this=0x8053a88, options=std::bitset = {...}, count=10, interleaveIn=cli::Cli::RUN_INTERLEAVE_DEFAULT) at Core/CLI/src/cli_run.cpp:140
#15 0xb7d6a42f in cli::RunCommand::Parse (this=0x80565d0, argv=std::vector of length 3, capacity 4 = {...}) at Core/CLI/src/cli_Commands.h:3654
#16 0xb7d5ae2c in cli::Parser::handle_command (this=0x8053c28, argv=std::vector of length 3, capacity 4 = {...}) at Core/CLI/src/cli_Parser.h:58
#17 0xb7d599ba in soar::tokenizer::parse_command (this=0xbfffefdc) at Core/shared/tokenizer.h:426
#18 0xb7d59758 in soar::tokenizer::evaluate (this=0xbfffefdc, input=0x8053288 "d 10") at Core/shared/tokenizer.h:344
#19 0xb7d4c5ad in cli::CommandLineInterface::Source (this=0x8053a88, buffer=0x8053288 "d 10", printFileStack=false) at Core/CLI/src/cli_source.cpp:255
#20 0xb7d5689f in cli::CommandLineInterface::DoCommand (this=0x8053a88, pConnection=0x80532e8, pAgent=0x8069bb0, pCommandLine=0x8053288 "d 10", echoResults=false, rawOutput=true, pResponse=0x80532c8) at Core/CLI/src/cli_CommandLineInterface.cpp:165
#21 0xb7cc043f in sml::KernelSML::HandleCommandLine (this=0x8053a40, pAgentSML=0x8069bb0, pCommandName=0x811d4e8 "cmdline", pConnection=0x80532e8, pIncoming=0xbffff238, pResponse=0x80532c8) at Core/KernelSML/src/sml_KernelSMLHandlers.cpp:1024
#22 0xb7cbc7c8 in sml::KernelSML::ProcessCommand (this=0x8053a40, pCommandName=0x811d4e8 "cmdline", pConnection=0x80532e8, pIncoming=0xbffff238, pResponse=0x80532c8) at Core/KernelSML/src/sml_KernelSML.cpp:613
#23 0xb7cbca34 in sml::KernelSML::ProcessIncomingSML (this=0x8053a40, pConnection=0x80532e8, pIncomingMsg=0xbffff350) at Core/KernelSML/src/sml_KernelSML.cpp:669
#24 0xb7cb3f01 in ReceivedCall (pConnection=0x80532e8, pIncoming=0xbffff350) at Core/KernelSML/src/KernelSMLInterface.cpp:38
#25 0xb7d23e95 in sml::Callback::Invoke (this=0x80595b8, pIncomingMessage=0xbffff350) at Core/ConnectionSML/src/sml_Connection.h:114
#26 0xb7d1e132 in sml::Connection::InvokeCallbacks (this=0x80532e8, pIncomingMsg=0xbffff350) at Core/ConnectionSML/src/sml_Connection.cpp:451
#27 0xb7cb40e9 in sml_ProcessMessage (hReceiverConnection=0x80532e8, hIncomingMsg=0x816d918, action=1) at Core/KernelSML/src/KernelSMLInterface.cpp:121
#28 0xb7d200d5 in sml::EmbeddedConnectionSynch::SendMsg (this=0x8053140, pMsg=0x810c5f0) at Core/ConnectionSML/src/sml_EmbeddedConnectionSynch.cpp:66
#29 0xb7d1e20d in sml::Connection::SendMessageGetResponse (this=0x8053140, pAnalysis=0xbffff47c, pMsg=0x810c5f0) at Core/ConnectionSML/src/sml_Connection.cpp:500
#30 0xb7d1e6b7 in sml::Connection::SendAgentCommand (this=0x8053140, pResponse=0xbffff47c, pCommandName=0xb7e35877 "cmdline", pAgentName=0x805ba7c "test", pParamName1=0xb7e34ba4 "line", pParamVal1=0xb6300474 "d 10", pParamName2=0xb7e34620 "echo", pParamVal2=0xb7e34091 "false", pParamName3=0xb7e34955 "nofilter", pParamVal3=0xb7e34091 "false", rawOutput=true) at Core/ConnectionSML/src/sml_Connection.cpp:688
#31 0xb7cf243e in sml::Kernel::ExecuteCommandLine (this=0x80596f8, pCommandLine=0xb6300474 "d 10", pAgentName=0x805ba7c "test", echoResults=false, noFilter=false) at Core/ClientSML/src/sml_ClientKernel.cpp:1228
#32 0xb7ced028 in sml::Agent::ExecuteCommandLine (this=0x811d4f8, pCommandLine=0xb6300474 "d 10", echoResults=false, noFilter=false) at Core/ClientSML/src/sml_ClientAgent.cpp:1368
#33 0x0804ca14 in CommandProcessor::process_line (this=0xbffff5b8, line="d 10") at TestCLI/testcli.h:299
#34 0x0804c6ce in CommandProcessor::loop (this=0xbffff5b8) at TestCLI/testcli.h:211
#35 0x0804ba7f in main (argc=2, argv=0xbffff6c4) at TestCLI/testcli.cpp:29
```

**Comment by mazina** [comment]
Fixed in 9.6.0
