### ISSUE TITLE
Eaters not working when updated Java from 1.8.0R40 to 1.8.0R45

### ISSUE THREAD

**Issue by brunoamelo** [SoarGroup/Soar#214]
It worked fine until Java version 1.8.0 release 40.
Today, during morning, I updated Java to 1.8.0 release 45, and Eaters.bat doesn't open anymore.
Do I need to alter Java settings or is this a bug?

Command line:
C:\Users\bruno.melo\Desktop\soar\soar>java -jar bin\Eaters_TankSoar.jar config\e
aters.cnf

Error received:
0    [main] WARN  com.commsen.stopwatch.Stopwatch  - Properties file stopwatch-e
ngine.properties not found on classpath! Properties not set!
Native code library failed to load.
java.lang.UnsatisfiedLinkError: no Java_sml_ClientInterface in java.library.path

Exception in thread "main" java.lang.UnsatisfiedLinkError: no Java_sml_ClientInt
erface in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at sml.smlJNI.<clinit>(smlJNI.java:15)
        at sml.Kernel.CreateKernelInNewThread(Kernel.java:128)
        at edu.umich.soar.gridmap2d.soar.Soar.<init>(Soar.java:88)
        at edu.umich.soar.gridmap2d.Simulation.initialize(Simulation.java:55)
        at edu.umich.soar.gridmap2d.Gridmap2D.<init>(Gridmap2D.java:95)
        at edu.umich.soar.gridmap2d.Gridmap2D.main(Gridmap2D.java:208)

C:\Users\bruno.melo\Desktop\soar\soar>

**Comment by bluechill** [comment]
This is possibly fixed by 1eb1f774e6bc94cb5ed54e733213ca3c0b9f8e45
