### ISSUE TITLE
[Tutorial] JavaSoarDebugger Missing Views

### ISSUE THREAD

**Issue by kierangilliam** [SoarGroup/Soar#330]
Hello, I'm following the Soar 9.6 tutorial on MacOS and have not been able to view all of the panels in the debugger. 

### Expected
![image](https://user-images.githubusercontent.com/18583882/108419729-c0258300-71e7-11eb-9192-e9a14a610fcd.png)

### Actual
![image](https://user-images.githubusercontent.com/18583882/108419167-0af2cb00-71e7-11eb-9795-e2211b50ee62.png)

### Steps to reproduce
Download and unzip [soar files](https://soar.eecs.umich.edu/articles/downloads/soar-suite/228-soar-tutorial-9-6-0).
`cd` into Soar directory
`sh SoarJavaDebugger.sh`
Goto System Preferences -> Security and allow the debugger to run.
Run the `sh SoarJavaDebugger.sh` command once more.
This is when I get the above screen.

If I navigate to Layouts > Use default window layout, I get the exception.
```
> Error loading file: /Users/kierangill/.SoarFiles/default-layout.dlf java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSGraphicsContext.graphicsPort()" because "<local3>" is null
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSGraphicsContext.graphicsPort()" because "<local3>" is null
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSGraphicsContext.graphicsPort()" because "<local3>" is null
	at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.custom.StyledTextRenderer.setFont(Unknown Source)
	at org.eclipse.swt.custom.StyledText.<init>(Unknown Source)
	at edu.umich.soar.debugger.modules.AbstractTextView.createDisplayControl(AbstractTextView.java:197)
	at edu.umich.soar.debugger.modules.AbstractComboView.init(AbstractComboView.java:263)
	at edu.umich.soar.debugger.manager.MainWindow.createInternalDefaultLayout(MainWindow.java:405)
	at edu.umich.soar.debugger.manager.MainWindow.useDefaultLayout(MainWindow.java:463)
	at edu.umich.soar.debugger.MainFrame.useDefaultLayout(MainFrame.java:700)
	at edu.umich.soar.debugger.menu.LayoutMenu.useDefaultPerformed(LayoutMenu.java:110)
	at edu.umich.soar.debugger.menu.LayoutMenu.access$000(LayoutMenu.java:24)
	at edu.umich.soar.debugger.menu.LayoutMenu$2.actionPerformed(LayoutMenu.java:42)
	at edu.umich.soar.debugger.menu.BaseMenu$2.widgetSelected(BaseMenu.java:108)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at edu.umich.soar.debugger.doc.Document.pumpMessagesTillClosed(Document.java:1104)
	at edu.umich.soar.debugger.SWTApplication.startApp(SWTApplication.java:298)
	at edu.umich.soar.debugger.Application.<init>(Application.java:31)
	at edu.umich.soar.debugger.Application.main(Application.java:54)
```
Note: the file `/Users/kierangill/.SoarFiles/default-layout.dlf` is present on my machine.

### Versions
MacOS Catalina 10.5.6
MacBook Pro (15-inch, 2019)
Intel i9 Processor
```
$ java --version
java 15.0.2 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
```

**Comment by kierangilliam** [comment]
[Related issue from a Salesforce project](https://github.com/forcedotcom/dataloader/issues/217)

[Commit to fix](https://github.com/forcedotcom/dataloader/commit/2515d08c1193f94ce16c6d1c6d579d289f1c0e08#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8)

**Comment by mazina** [comment]
Just to be clear, if you click on step before you do anything else, nothing appears in any window?  If that's the case, I was not able to recreate your issue.  I downloaded a fresh copy of the tutorial and was able to run it under both java 8 and java 15.  

Here are a few things you could try:

1. Delete the .SoarFiles directory and relaunch.  We have seen cases where the settings file is corrupted, which prevents the debugger from launching properly.  

2. Try it under java 8.  (IIRC, you can install multiple versions of java on the same machine and then switch between them with the java_home command.)

3. Recompile from source.  if the problem you're seeing is similar to the one you linked to, perhaps their solution of rebuilding against a new version of the SWT library will also work.

(I can confirm I get the same java exception when switching layouts.  That's not a feature that I ever use, so it's possible that bug has been there for a while.  You shouldn't need to use the custom layouts to use the debugger.)

**Comment by mazina** [comment]
The link you posted suggested that what you saw might be linked to OSX Big Sur.  I've recently upgraded to Big Sur, but I still can't recreate the problem you see.

I'll leave this issue open for now, in case other people might be seeing something similar.

**Comment by kierangilliam** [comment]
Sorry for taking a while to get back to you and thanks for the responsiveness.

We can close the issue as I opted to setup a Docker + Jupyter Notebook environment instead.

In case this may be useful to others, I've been [rewriting the Soar tutorials](https://github.com/kierangilliam/soar) in Jupyter Notebooks for my classmates. It's riddled with TODOs right now as it's a WIP. However, I'd love some feedback on it, if anyone has any!

**Comment by mazina** [comment]
Hi, Kieran.  I checked out your Jupyter notebooks.  I wanted to ask you a question, but I couldn't find a way to contact.  Could you send me an e-mail with your info?
