### ISSUE TITLE
Soar Debugger- java.lang.UnsatifiedLinkError: Can't find dependent libraries

### ISSUE THREAD

**Issue by precupstefan** [SoarGroup/Soar#517]
Hi!

I have a project written in Python, from which I spawn the debugger.

The project runs for a couple of times (and I can interact with the debugger), after which I get the error whenever I try to run it again:

`java.lang.UnsatisfiedLinkError: <path>\Java_sml_ClientInterface.dll: Can't find dependent libraries
Exception in thread "main" java.lang.UnsatisfiedLinkError: <path>\Java_sml_ClientInterface.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:251)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2432)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base/java.lang.System.loadLibrary(System.java:2068)
	at sml.smlJNI.<clinit>(smlJNI.java:15)
	at sml.Kernel.GetDefaultPort(Kernel.java:180)
	at edu.umich.soar.debugger.SWTApplication.startApp(SWTApplication.java:172)
	at edu.umich.soar.debugger.Application.<init>(Application.java:31)
	at edu.umich.soar.debugger.Application.main(Application.java:54)
`

I looked at error #509 , but this doesn't fix it.   Spawning debugger from SoarDebugger.bat and then connecting to agent works.

I'm running this on Windows.

**Comment by precupstefan** [comment]
Ok so I figured it out after 4 hours of troubleshooting (and few minutes after posting).

The culprit was a production rule I added.

```
sp {ol*complete
   (state <s> ^operator <o> ^io.output-link <ol>)
   (<ol> ^status complete)
-->
   (<ol> ^status - ^test -)
   (<s> ^operator <o> -)}
```
   
   However, the behaviour is quite strange. Why has this rule caused the Debugger to stop working?
   
   In case you're wondering this is the entire code:
   
   ```

sp {minigrid*propose*test
   (state <s> ^name minigrid
              ^io.input-link <ol>)
-->
   (<s> ^operator <op> + =)
   (<op> ^name test)
}

sp {apply*test
   (state <s> ^operator <op> ^io.output-link <ol>)
   (<op> ^name test)
-->
   (write (crlf) | 2|)
   (<ol> ^test 2)
}

#sp {ol*complete
#   (state <s> ^operator <o> ^io.output-link <ol>)
#   (<ol> ^status complete)
#-->
#   (<ol> ^status - ^test -)
#   (<s> ^operator <o> -)}

```

**Comment by garfieldnate** [comment]
I'm sorry I never replied to this before, but I can't make heads or tails of this. It's a very strange error, and it makes me wonder if there was something else going on on your computer that may have caused this. I can't think of any reason that adding a production would cause the Java bindings not to be found.

**Comment by precupstefan** [comment]
The rule had some errors. When loading that rule with the error, the debugger would not spawn. I will test again tomorrow with a different agent I am writing to check if this behavior is reproductible.
