### ISSUE TITLE
Support Linux on ARM processor

### ISSUE THREAD

**Issue by BenJMaybeSteveJobs** [SoarGroup/Soar#525]
Unable to run the debugger, any help would be appreciated, thank you.

[fedora@fedora SoarSuite_9.6.3-Multiplatform]$ ./SoarJavaDebugger.sh
[fedora@fedora SoarSuite_9.6.3-Multiplatform]$ Native code library failed to load. 
java.lang.UnsatisfiedLinkError: /home/fedora/Downloads/SoarSuite_9.6.3-Multiplatform/bin/libJava_sml_ClientInterface.so: /home/fedora/Downloads/SoarSuite_9.6.3-Multiplatform/bin/libJava_sml_ClientInterface.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/fedora/Downloads/SoarSuite_9.6.3-Multiplatform/bin/libJava_sml_ClientInterface.so: /home/fedora/Downloads/SoarSuite_9.6.3-Multiplatform/bin/libJava_sml_ClientInterface.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at sml.smlJNI.<clinit>(smlJNI.java:15)
	at sml.Kernel.GetDefaultPort(Kernel.java:180)
	at edu.umich.soar.debugger.SWTApplication.startApp(SWTApplication.java:172)
	at edu.umich.soar.debugger.Application.<init>(Application.java:31)
	at edu.umich.soar.debugger.Application.main(Application.java:54)
[fedora@fedora SoarSuite_9.6.3-Multiplatform]$

**Comment by garfieldnate** [comment]
We don't currently build or distribute ARM Linux binaries, although Soar does build just fine for it. For now, if you want to use Soar on Linux with an ARM processor, you'll need to build it yourself. I'll ask internally if we can prioritize adding this build before the next release.

Out of curiosity, what is your use-case for Soar? Not many have used it with an ARM processor thus far (we do have one party that builds Soar themselves for it).
